version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      znet:
        ipv4_address: 192.168.0.27
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zt-db
    ports:
      - '5432:5432'
    networks:
      znet:
        ipv4_address: 192.168.0.28

networks:
  znet:
    external: true